# Generated by Django 3.2.5 on 2021-07-17 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colaborador', '0002_colaborador_no_setor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_documento', models.CharField(help_text='Nome do documento', max_length=100)),
                ('descricao_do_documento', models.TextField(help_text='Faça uma breve descrição sobre este documento')),
                ('slug', models.SlugField(help_text='Padrão de referencia', max_length=100, null=True, unique=True)),
                ('data_modificaao', models.DateTimeField(auto_now=True, help_text='Data da criação do arquivo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, help_text='Data da criação do arquivo')),
                ('a_quem_pertence', models.ForeignKey(help_text='A quem pertence o arquivo', on_delete=django.db.models.deletion.PROTECT, related_name='pertence_a', to='colaborador.colaborador')),
            ],
        ),
    ]
