# Generated by Django 3.2.5 on 2021-07-17 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_colaborador', models.CharField(help_text='Nome do colaboradores', max_length=100)),
                ('slug', models.SlugField(help_text='Padrão de referencia', max_length=100, null=True, unique=True)),
                ('data_modificaao', models.DateTimeField(auto_now=True, help_text='Data da criação do arquivo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, help_text='Data da criação do arquivo')),
                ('nome_usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='user_name_test', to=settings.AUTH_USER_MODEL)),
                ('trabalha_na_empresa', models.ForeignKey(help_text='Em qual empresa o colaborador trabalha', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='onde_trabalha', to='empresa.empresa')),
            ],
        ),
    ]
