# Generated by Django 3.2.5 on 2021-07-17 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
        ('colaborador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='no_setor',
            field=models.ForeignKey(help_text='Em qual setor', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='em_qual_setor', to='departamento.departamento'),
        ),
    ]
