# Generated by Django 3.2.5 on 2021-07-26 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0002_colaborador_no_setor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaborador',
            old_name='nome_usuario',
            new_name='user',
        ),
    ]
