# Generated by Django 3.2.5 on 2021-07-26 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0003_rename_nome_usuario_colaborador_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaborador',
            old_name='user',
            new_name='user_data',
        ),
    ]
