# Generated by Django 3.2.5 on 2021-07-26 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0004_rename_user_colaborador_user_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaborador',
            old_name='user_data',
            new_name='user',
        ),
    ]
