# Generated by Django 3.2.5 on 2021-07-27 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0005_rename_user_data_colaborador_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaborador',
            old_name='no_setor',
            new_name='nome_departamento',
        ),
        migrations.RenameField(
            model_name='colaborador',
            old_name='trabalha_na_empresa',
            new_name='nome_empresa',
        ),
    ]
