# Generated by Django 3.2.5 on 2021-08-11 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0007_rename_nome_departamento_colaborador_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaborador',
            old_name='empresa',
            new_name='nome_departamento',
        ),
    ]
