# Generated by Django 3.2.5 on 2021-08-12 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_rename_nome_da_empresa_empresa_nome_empresa'),
        ('colaborador', '0008_rename_empresa_colaborador_nome_departamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaborador',
            old_name='nome_departamento',
            new_name='no_setor',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='nome_empresa',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='trabalha_na_empresa',
            field=models.ForeignKey(blank=True, help_text='Em qual empresa o colaborador trabalha', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='onde_trabalha', to='empresa.empresa'),
        ),
    ]
