# Generated by Django 3.2.5 on 2021-08-12 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0009_auto_20210811_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaborador',
            old_name='no_setor',
            new_name='nome_departamento',
        ),
        migrations.RenameField(
            model_name='colaborador',
            old_name='trabalha_na_empresa',
            new_name='nome_empresa',
        ),
    ]
