# Generated by Django 3.2.5 on 2021-08-12 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresa', '0002_rename_nome_da_empresa_empresa_nome_empresa'),
        ('colaborador', '0010_auto_20210811_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='nome_empresa',
            field=models.ForeignKey(blank=True, help_text='Em qual empresa o colaborador trabalha', null=True, on_delete=django.db.models.deletion.PROTECT, to='empresa.empresa'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
