# Generated by Django 3.2.5 on 2021-07-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_departamento', models.CharField(help_text='Digite o nome do departamento', max_length=100)),
                ('descricao_do_departamento', models.TextField(help_text='Faça uma breve descriçao sobre o departamento')),
                ('slug', models.SlugField(help_text='Padrão de referencia', max_length=100, null=True, unique=True)),
                ('data_modificaao', models.DateTimeField(auto_now=True, help_text='Data da criação do arquivo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, help_text='Data da criação do arquivo')),
            ],
        ),
    ]
