# Generated by Django 3.2.5 on 2021-07-27 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_hora_extra', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrohoraextra',
            old_name='pertence_a',
            new_name='nome_colaborador',
        ),
    ]
