# Generated by Django 3.2.5 on 2021-07-27 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='nome_da_empresa',
            new_name='nome_empresa',
        ),
    ]
